### ISSUE TITLE
InvalidAccessKeyId error during upgrade

### ISSUE THREAD

**Issue by vrutkovs** [openshift/cluster-image-registry-operator#173] opened 2019-01-28 16:01 UTC
Image registry operator works fine after cluster is setup, but broken after upgrade:

* `oc get clusteroperator cluster-image-registry-operator -o yaml`:
```
...
  - lastTransitionTime: 2019-01-28T15:48:03Z
    message: "Unable to apply resources: unable to sync storage configuration: InvalidAccessKeyId:
      The AWS Access Key Id you provided does not exist in our records.\n\tstatus
      code: 403, request id: 1BB1FAF4B272F4A2, host id: 5/5II1d/1rTqEEh9HbyiW+P8NM+dqzd0NOCpmTogNIjgFoRf7lSxbdyX0BWhH1B+9ILNI22u9Lw="
    status: "True"
    type: Progressing
...
```
* image-registry pods are being restarted frequently, so builds fail with HTTP 500

**Comment by bparees** [comment] 2019-01-28 16:15
possibly a problem w/ the credentials minter deleting the creds it gave us?

**Comment by smarterclayton** [comment] 2019-01-29 18:14
hot looping bad1!!!!!!

**Comment by bparees** [comment] 2019-01-29 18:47
so @coreydaley there are two issues:

1) why did the key become invalid (was the existing key removed during the upgrade?  was the key changed as part of the upgrade and the new key isn't valid?)  Guessing this is related to credential minting.

2) why are we hotlooping on the access failure.

**Comment by coreydaley** [comment] 2019-01-29 19:10
@sjenning What does your config look like? 
`oc get configs.imageregistry.operator.openshift.io -o yaml`

**Comment by bparees** [comment] 2019-01-29 20:49
/cc @dgoodwin 

sounds like all of this is caused by bad minted creds (and/or creds being updated when they should not be)

**Comment by coreydaley** [comment] 2019-01-29 20:52
It looks like the initial set of credentials was correct and the storage was created, tagged, etc, then on the resync they were incorrect (according to the config & conditions)

**Comment by dgoodwin** [comment] 2019-01-29 21:14
The cred minter logs show successfully created the secret, and then on the next sync it says the secret does not exist. Could anything else be deleting that secret?

**Comment by coreydaley** [comment] 2019-01-29 21:30
@dgoodwin I'm checking to see if anything in the operator might be deleting it.

**Comment by dgoodwin** [comment] 2019-01-30 12:11
From the logs I got it appears it's happening for all three creds the operator manages, so unlikely anything in the operator. Will be filing an issue this morning with everything I can come up with. I don't immediately know how to fix a hotloop that creates a secret, resyncs, and then can't see the secret it created, which appears to be what happened. I am curious if anything else was in trouble in the cluster post upgrade.

**Comment by bparees** [comment] 2019-01-30 14:59
@dgoodwin ok, please link the issue you open once you do so, i intend to close this one in deference to that.

**Comment by dgoodwin** [comment] 2019-01-30 15:22
https://github.com/openshift/cloud-credential-operator/issues/24

**Closed** 2019-01-30 15:30 UTC
